const DORK_TEMPLATES = {
  bounty: {
    label: 'Bug Bounty Programs',
    icon: 'fa-bug',
    color: '#10b981',
    dorks: [
      'inurl:/bug-bounty "security"',
      'inurl:/security "bug bounty"',
      'intext:"bug bounty" inurl:/report',
      'intext:"we offer a bounty"',
      'intext:"security vulnerability" "eligible for reward"',
      '"bug bounty" "reward" "scope" -hackerone.com -bugcrowd.com -medium.com',
      '"bug bounty program" "report vulnerability" "reward"',
      'inurl:"bug bounty" and intext:"$" and inurl:/security',
      'inurl:"bug bounty" and intext:"€" and inurl:/security',
      'inurl:"bug bounty" and intext:"INR" and inurl:/security',
      'intext:"BugBounty" and intext:"BTC" and intext:"reward"',
      '"bug bounty" intext:"BTC" | "ETH" | "USDT" | "crypto" | "reward"',
      'intext:bounty inurl:/security',
      'inurl:responsible disclosure $50',
      'inurl:bug bounty $50',
      'inurl:bounty $50',
      '"we pay" security researchers vulnerability',
      '"cash reward" "security vulnerability" report',
      '"monetary reward" "vulnerability" "disclosure"',
      '"eligible for a reward" security vulnerability',
      '"security reward" "up to" "$" vulnerability',
      '"If you find a security issue" "reward"',
      '"responsible disclosure" intext:"you may be eligible for monetary compensation"',
      '"vulnerability disclosure program" AND (bounty OR reward OR swag OR "hall of fame")',
      '"responsible disclosure" AND (monetary OR cash OR "gift card" OR crypto OR BTC)',
      'intext:"security vulnerability" "report"',
      'intext:"submit vulnerability" | "security vulnerability report" | "bug bounty reward"',
      '"security bounty" program scope eligible reward',
      '"bounty program" "in scope" "out of scope"',
      '"bug bounty" "safe harbor" reward',
      '"bug bounty" "cryptocurrency" OR "bitcoin" reward',
      'inurl:bug bounty intext:"rupees"',
      'inurl:bug bounty intext:"₹"',
    ]
  },

  disclosure: {
    label: 'Responsible Disclosure',
    icon: 'fa-shield-alt',
    color: '#3b82f6',
    dorks: [
      'inurl:/responsible disclosure',
      'inurl:/responsible-disclosure/ reward',
      'inurl:/responsible-disclosure/ swag',
      'inurl:/responsible-disclosure/ bounty',
      'inurl:responsible-disclosure-policy',
      'inurl:vulnerability-disclosure-policy reward',
      'inurl:reporting-security-issues',
      'inurl:/trust/report-a-vulnerability',
      '"vulnerability reporting policy"',
      '"If you believe you\'ve found a security vulnerability"',
      '"coordinated vulnerability disclosure" policy',
      '"we take security very seriously"',
      '"submit vulnerability report"',
      '"submit vulnerability report" | "powered by bugcrowd" | "powered by hackerone"',
      '"submit vulnerability report" -site:hackerone.com -site:bugcrowd.com -site:synack.com -site:openbugbounty.org',
      '"vulnerability disclosure policy" -hackerone -bugcrowd',
      '"responsible disclosure policy" security report',
      '"if you discover" "security vulnerability" "contact"',
      '"security policy" "report" "vulnerability" "responsible"',
      '"we take security seriously" "report" "vulnerability"',
      '"report a vulnerability" "security team" email',
      '"If you discover a vulnerability" AND (swag OR "hall of fame" OR monetary)',
      '"We value security researchers" OR "We appreciate security reports" AND (reward OR bounty)',
      'intitle:"Bug Bounty" OR intitle:"Vulnerability Disclosure" OR intitle:"Security Rewards"',
      'inurl:"responsible disclosure", "bug bounty", "bugbounty"',
      'responsible disclosure inurl:in',
    ]
  },

  securityTxt: {
    label: 'security.txt Files',
    icon: 'fa-file-alt',
    color: '#f97316',
    dorks: [
      'inurl:security.txt',
      'inurl:/security.txt "bug bounty"',
      'inurl:/.well-known/security.txt "bug bounty"',
      'inurl:/.well-known/security ext:txt',
      'inurl:/.well-known/security ext:txt intext:hackerone',
      'inurl:/.well-known/security ext:txt -hackerone -bugcrowd -synack -openbugbounty',
      'inurl:/.well-known/security.txt intext:bounty -hackerone -bugcrowd -synack',
      'inurl:/security.txt "mailto*" -github.com -wikipedia.org -portswigger.net -magento',
      'inurl:security.txt intext:"mailto" -github.com -wikipedia.org -portswigger.net -magento',
      'inurl:security-policy.txt ext:txt',
      'inurl:/security ext:txt "contact"',
      'site:*/security.txt "bounty"',
      '"security.txt" AND ("mailto" OR "contact") AND (bounty OR reward)',
      '"security.txt" AND "PGP" AND (bounty OR reward)',
      '"security@*" AND ("bug bounty" OR "vulnerability disclosure") ext:txt',
      'filetype:txt security reward rewards -"we currently" -"we do not" -"not offer"',
      'inurl:"security.txt" intext:"$"',
      '"Contact:" "Expires:" "Policy:" security.txt',
      '"Contact:" "Policy:" "Acknowledgments:" security',
    ]
  },

  swag: {
    label: 'Swag Programs',
    icon: 'fa-gift',
    color: '#f59e0b',
    dorks: [
      'inurl:\'/responsible disclosure\' hoodie',
      '"responsible disclosure" "swag" -hackerone -bugcrowd',
      '"report vulnerability" "swag" "t-shirt"',
      '"vulnerability disclosure" "swag" "merchandise"',
      '"bug bounty" "swag" "goodies" -medium.com',
      '"security researcher" "swag" "acknowledgment"',
      '"responsible disclosure" "hoodie" security',
      '"we send swag" security researcher',
      '"swag pack" "security" "vulnerability"',
      '"vulnerability report" "swag" OR "merch" OR "merchandise"',
      '"security disclosure" "t-shirt" OR "hoodie" OR "sticker"',
      'responsible disclosure swag',
    ]
  },

  hof: {
    label: 'Hall of Fame',
    icon: 'fa-trophy',
    color: '#8b5cf6',
    dorks: [
      'responsible disclosure hall of fame',
      '"hall of fame" "security researchers" "reported"',
      '"security acknowledgements" "reported by"',
      '"wall of fame" "security" "vulnerability"',
      '"thank you" "security researchers" "responsible disclosure"',
      '"security thanks" "vulnerability" "reported"',
      '"hall of fame" "responsible disclosure"',
      '"we would like to thank" "security" researcher',
      '"bug hunters" "hall of fame"',
      '"security hall of fame" vulnerability report',
      '"acknowledged" "security researchers" vulnerability',
      'responsible disclosure white hat',
      'white hat program',
    ]
  },

  platforms: {
    label: 'Platform-Powered',
    icon: 'fa-server',
    color: '#06b6d4',
    dorks: [
      '"powered by bugcrowd" -site:bugcrowd.com',
      '"powered by hackerone" -site:hackerone.com',
      '"powered by yeswehack" OR "powered by federacy" OR "powered by intigriti" -site:yeswehack.com -site:federacy.com -site:intigriti.com',
      '"powered by synack"',
      '"Powered by Bug Bounty HQ" OR "Powered by disclose.io"',
      '"managed by huntr.dev"',
      '"Submission Form powered by Bugcrowd" -bugcrowd.com',
      'inurl:/hackerone.yml -site:hackerone.com',
      'inurl:/bug-bounty.json | inurl:/vdp.json',
      '"submit vulnerability" -hackerone.com -bugcrowd.com -synack.com',
      '"report security issue" -hackerone -bugcrowd -github',
      'site:responsibledisclosure.com',
      '"disclose.io" security vulnerability report',
    ]
  },

  govMil: {
    label: 'Government & Military',
    icon: 'fa-landmark',
    color: '#ef4444',
    dorks: [
      'site:*.gov.* "responsible disclosure"',
      'site:*.gov* "vulnerability disclosure program" OR "bug bounty"',
      'site:*.gov* inurl:/security intext:contact intext:reward',
      'site:*.gov* filetype:pdf "vulnerability disclosure policy"',
      'site:.gov. "responsible disclosure"',
      'site:.mil. "security vulnerability report"',
      'site:gov "vulnerability disclosure" report',
      'site:gov "bug bounty" OR "responsible disclosure"',
      'site:gov "security.txt" contact',
      'site:gov.in "security" "report vulnerability"',
      'site:gov.uk "vulnerability disclosure"',
      'site:gov.au "responsible disclosure"',
    ]
  },

  education: {
    label: 'University & Education',
    icon: 'fa-graduation-cap',
    color: '#a78bfa',
    dorks: [
      'site:*.edu intext:security report vulnerability',
      'site:*.edu "responsible disclosure" AND (reward OR swag OR bounty)',
      'site:*.edu inurl:/security intext:"report a vulnerability"',
      'site:*.edu intext:"we run a bug bounty program"',
      'site:*.edu intext:"vulnerability disclosure policy" intext:hall_of_fame',
      'site:*.edu intext:"security report reward"',
      'site:*.edu "security researchers" "hall of fame"',
      '"responsible disclosure" university',
      'inurl:/responsible-disclosure/ university',
    ]
  },

  europe: {
    label: 'Europe',
    icon: 'fa-globe-europe',
    color: '#ec4899',
    dorks: [
      'site:*.nl responsible disclosure reward',
      'site:*.nl intext:security report reward',
      'site:*.nl intext:responsible disclosure reward',
      'intext:Vulnerability Disclosure site:nl',
      'site:*.de inurl:bug inurl:bounty',
      'site:*.uk intext:security report reward',
      'site:*.eu intext:security report reward',
      'intext:Vulnerability Disclosure site:eu',
      'responsible disclosure europe',
      'site:*.be responsible disclosure',
      'site:*.at responsible disclosure',
      'site:*.fr intext:"bug bounty" OR "prime de sécurité"',
      'site:*.it intext:"bug bounty" OR intext:"security reward"',
      'site:*.ch filetype:txt inurl:security intext:bounty',
      'site:*.se intext:"responsible disclosure" intext:hall_of_fame',
      'site:*.dk inurl:/sikkerhed intext:dusør',
      'site:*.no inurl:/sikkerhet intext:belønning',
      'site:*.es inurl:/seguridad intext:recompensa',
      'site:*.pl inurl:/bezpieczenstwo intext:nagroda',
      '"van de melding met een minimum van een" -site:responsibledisclosure.nl',
    ]
  },

  asiaPacific: {
    label: 'Asia & Pacific',
    icon: 'fa-globe-asia',
    color: '#f472b6',
    dorks: [
      'site:*.in responsible disclosure bounty',
      'inurl:responsible disclosure intext:"INR"',
      'site:*.jp intext:"vulnerability report" intext:swag',
      'site:*.cn intext:security report reward',
      'site:*.au responsible disclosure bounty',
      'site:*.au responsible disclosure',
    ]
  },

  americas: {
    label: 'Americas',
    icon: 'fa-globe-americas',
    color: '#fb923c',
    dorks: [
      'site:*.br responsible disclosure',
      'site:*.br responsible disclosure bounty',
      'site:*.ca intext:"responsible disclosure" intext:reward',
      'site:*.com intext:security report reward',
    ]
  },

  fintech: {
    label: 'Fintech & Crypto',
    icon: 'fa-coins',
    color: '#84cc16',
    dorks: [
      '"bug bounty" crypto OR blockchain OR exchange reward',
      'intext:"cryptocurrency" "bug bounty"',
      'site:*.exchange intext:security vulnerability report',
      'inurl:security-report intext:crypto | blockchain | token',
      '"security vulnerability" fintech OR payment OR banking report',
      '"bug bounty" defi OR web3 OR "smart contract"',
      '"vulnerability disclosure" cryptocurrency OR wallet OR exchange',
      '"security reward" payment OR bank OR finance report',
      '"bug bounty" nft OR token OR protocol reward',
      '"responsible disclosure" trading OR exchange security',
      'buy bitcoins "bug bounty"',
      'site:*.bank "security vulnerability report"',
      'site:*.finance "bug bounty"',
    ]
  },

  ecommerce: {
    label: 'E-commerce & Payments',
    icon: 'fa-shopping-cart',
    color: '#14b8a6',
    dorks: [
      'site:*.shop intext:"bug bounty"',
      'site:*.store intext:"responsible disclosure"',
      'site:*.pay intext:"security vulnerability report"',
      'intext:"if you find a vulnerability" site:*.bank',
    ]
  },

  cms: {
    label: 'CMS & Open Source',
    icon: 'fa-code-branch',
    color: '#a855f7',
    dorks: [
      '"cms" bug bounty',
      '"open-source security bounty"',
      'inurl:/.git intext:security vulnerability',
      'inurl:/wp-content/plugins/ intext:vulnerability report',
      'inurl:/modules/security-report/',
      'site:github.com "SECURITY.md" "bounty" OR "reward"',
      'site:github.com "security policy" "vulnerability" "reward"',
      'site:gitlab.com "responsible disclosure" "reward"',
      '"open source" "bug bounty" "security" reward',
      '"oss" "bug bounty" security report reward',
      'site:github.com SECURITY.md "report vulnerabilities"',
    ]
  },

  advanced: {
    label: 'Advanced & Unique',
    icon: 'fa-crosshairs',
    color: '#e879f9',
    dorks: [
      'inurl:/security/index.html intext:bounty',
      'inurl:/legal/security intext:monetary',
      'intext:"CVSS score" AND "eligible for a reward" -hackerone -bugcrowd',
      'inurl: private bugbountyprogram',
      'intext:security report monetary inurl:security',
      'intext:security report reward inurl:report',
      'site:security.*.* inurl: bounty',
      'site:help.*.* inurl:bounty',
      'site:support.*.* intext:security report reward',
      'site:*.*.* inurl:bug inurl:bounty',
      'inurl:/s/ intext:responsible disclosure',
      'inurl:/s/ intext:bugbounty',
    ]
  },

  wideScan: {
    label: 'Wide Scan (High Volume)',
    icon: 'fa-satellite',
    color: '#38bdf8',
    dorks: [
      'inurl:/security "reward"',
      'intext:responsible disclosure',
      'intext:responsible disclosure bounty',
      '"security vulnerability" "report"',
      '"responsible disclosure" "bounty" "reward"',
      'responsible disclosure',
      'inurl:/bug bounty',
      'inurl:/security',
      '"powered by hackerone" "submit vulnerability report"',
      '"report a security bug" reward bounty',
      '"security bug bounty" policy reward eligible',
    ]
  },
};

module.exports = { DORK_TEMPLATES };
